### ISSUE TITLE
Criteria for  business success 

### ISSUE THREAD

**Issue by Pitso-Paballo** [Pitso-Paballo/Innovate-Six#9]
List our criteria for the success of the business.

**Comment by SimphiweMecheall** [comment]
**Our criteria for business success include:**
• Deployment along with the effective adoption of the AI tool in the classroom or home setting.
• It is observable that after the use of the tool, the children have a better development of their pronunciation, writing, and math skills.
• Complimentary comments from teachers, parents, and children throughout the year about both the educational benefits of the tool.
